version: '3.8'
services:
  users-service:
    build:
      context: ./usersService
    image: users-service
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./usersService/users.json:/app/users.json
      
  locations-service:
    build:
      context: ./locationsService
    image: locations-service
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./locationsService/src/data/locations.json:/app/locations.json
      
  users-locations-vanila-client:
    build:
      context: ./vanilaClient
    image: users-locations-vanila-client
    ports:
      - "8080:8080"
    depends_on:
      - locations-service
      - users-service
